# Generated by Django 2.1.7 on 2019-02-18 04:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0002_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggest',
            name='name_text',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
